#!/usr/bin/env bash
# Shared runtime config for the all-in-one container. Internal services all live
# on localhost inside this one container (matching the app's default hostnames),
# so there is no Docker network / DNS / multi-port surface.
# supervisord drops privileges (user=neuroinsight) but doesn't reset HOME, so it
# stays /root and ~ resolves wrong. Pin it so ssh + ~/.ssh/config (saved-host
# aliases) and other HOME-relative lookups work.
export HOME=/home/neuroinsight
export ENVIRONMENT=production
export DATABASE_URL="postgresql://neuroinsight@127.0.0.1:5432/neuroinsight"
export REDIS_HOST=127.0.0.1
export REDIS_PORT=6379
export MINIO_HOST=127.0.0.1
export MINIO_PORT=9000
export MINIO_SECURE=false
export DATA_DIR=/data
export BACKEND_TYPE="${BACKEND_TYPE:-local}"

# Per-install secrets generated by entrypoint.sh on first run. The fallbacks keep
# a bare local dev run (without the entrypoint) working; in the shipped container
# the file always exists, so the defaults below are never used.
# shellcheck disable=SC1091
[ -f /data/secrets.env ] && . /data/secrets.env
export REDIS_PASSWORD="${REDIS_PASSWORD:-nirredis}"
export MINIO_ROOT_USER="${MINIO_ROOT_USER:-niradmin}"
export MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-nirminio123}"
# The app reads MINIO_ACCESS_KEY/SECRET_KEY; minio server reads MINIO_ROOT_*.
export MINIO_ACCESS_KEY="${MINIO_ROOT_USER}"
export MINIO_SECRET_KEY="${MINIO_ROOT_PASSWORD}"
export SECRET_KEY="${SECRET_KEY:-nir-allinone-development-secret-key-change-me}"
