"""initial schema - jobs table

Revision ID: e25556f4711f
Revises: 
Create Date: 2026-02-11 20:32:46.777647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25556f4711f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique job identifier (UUID)'),
    sa.Column('backend_type', sa.String(length=50), nullable=False, comment='Execution backend: local_docker or slurm'),
    sa.Column('backend_job_id', sa.String(length=100), nullable=True, comment='Scheduler-specific job ID'),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=True),
    sa.Column('container_image', sa.String(length=200), nullable=False),
    sa.Column('input_files', sa.JSON(), nullable=False, comment='Array of input file paths'),
    sa.Column('parameters', sa.JSON(), nullable=False, comment='Pipeline execution parameters'),
    sa.Column('resources', sa.JSON(), nullable=False, comment='Computational resource allocation'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current execution status'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Estimated progress percentage (0-100)'),
    sa.Column('current_phase', sa.String(length=120), nullable=True, comment='Current pipeline phase label'),
    sa.Column('submitted_at', sa.DateTime(), nullable=False, comment='Job submission timestamp'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Execution start timestamp'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Execution completion timestamp'),
    sa.Column('output_dir', sa.String(length=500), nullable=False, comment='Path to job output directory'),
    sa.Column('exit_code', sa.Integer(), nullable=True, comment='Process exit code (0=success)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Failure reason or error message'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='User ID (multi-user mode)'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Job creator username'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='User-defined tags (array of strings)'),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deleted', 'jobs', ['deleted'], unique=False)
    op.create_index('idx_status_submitted', 'jobs', ['status', 'submitted_at'], unique=False)
    op.create_index('idx_user_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_backend_job_id'), 'jobs', ['backend_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_backend_type'), 'jobs', ['backend_type'], unique=False)
    op.create_index(op.f('ix_jobs_deleted'), 'jobs', ['deleted'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_pipeline_name'), 'jobs', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_submitted_at'), 'jobs', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_submitted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_pipeline_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_deleted'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_backend_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_backend_job_id'), table_name='jobs')
    op.drop_index('idx_user_status', table_name='jobs')
    op.drop_index('idx_status_submitted', table_name='jobs')
    op.drop_index('idx_deleted', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
